import type { Metadata } from 'next'
// eslint-disable-next-line camelcase
import { New_Rocker } from 'next/font/google'
import './globals.css'

const newRocker = New_Rocker({
  subsets: ['latin'],
  weight: '400',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="pt-br">
      <body
        className={`${newRocker.className} bg-black text-slate-50 antialiased`}
      >
        {children}
      </body>
    </html>
  )
}
